github: aliasfoxkde
ko_fi: aliasfoxkde
buy_me_a_coffee: aliasfoxkde
custom:
  - name: "Buy Me A Coffee"
    url: https://www.buymeacoffee.com/aliasfoxkde
  - name: "GitHub Sponsors"
    url: https://github.com/sponsors/aliasfoxkde
